### ISSUE TITLE
Nightly build does not start, pipewire-pulse

### ISSUE THREAD

**Issue by Shinigamiixd** [theRealCarneiro/pulsemeeter#107]
```
[DEBUG] in [logger@init_log]: started logger instance <Logger generic (DEBUG)> at thread 23593
[DEBUG] in [pmctl@runcmd]: pmctl init sink Virtual_Input_1 2
[DEBUG] in [pmctl@runcmd]: pmctl init sink Virtual_Input_2 2
Could not start server because of:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pulsemeeter/main.py", line 16, in start_server
    server.start_server(daemon=True)
  File "/usr/lib/python3.10/site-packages/pulsemeeter/api/audio_server.py", line 58, in start_server
    self.init_audio()
  File "/usr/lib/python3.10/site-packages/pulsemeeter/api/audio_server.py", line 49, in init_audio
    self.start_sources()
  File "/usr/lib/python3.10/site-packages/pulsemeeter/api/audio_server.py", line 266, in start_sources
    channels = device_config['channels']
KeyError: 'channels'
```

 - Distro: Arch Linux
 - Python Version: Python 3.10.9
 - I have pipewire-pulse downloaded

I built nightly from source/not script, as script was spewing errors

**Comment by W0lfyZRex** [comment]
Bump, I'm having the same issue and I'm using nightly because the main branch has the "JSON stray \ before #" error.

**Comment by Erater** [comment]
I got the same error as @W0lfyZRex main branch is broken with JSON stray  and nightly wont start cause of this error, would be nice if there is a fix

**Comment by erdnuesse** [comment]
Take a look at this PR, it fixes the Stray / error. 
I fixed it manually in my /usr/bin/pmctl; error vanished, pulsemeeter starts.
