### ISSUE TITLE
Pulsemeeter GUI wont start

### ISSUE THREAD

**Issue by stiw47** [theRealCarneiro/pulsemeeter#115]
**Describe the bug**
Archlinux with KDE. Pulsemeeter GUI wont start, either if run by clicking on pulsemeeter.desktop from menu, or run from command line by executing `pulsemeeter`.

**To Reproduce**
1. As said above, either: search for the Pulsemeeter in menu. or execute `pulsemeeter` from Terminal
2. See error from Terminal:

```
[stiw47@archmedia ~]$ pulsemeeter

(pulsemeeter:9281): Gtk-WARNING **: 08:12:04.811: Locale not supported by C library.
	Using the fallback 'C' locale.
ERROR: invalid json 
Traceback (most recent call last):
  File "/usr/bin/pulsemeeter", line 33, in <module>
    sys.exit(load_entry_point('pulsemeeter==1.2.14', 'console_scripts', 'pulsemeeter')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pulsemeeter/__main__.py", line 481, in main
    start_app(isserver, trayonly)
  File "/usr/lib/python3.11/site-packages/pulsemeeter/__main__.py", line 423, in start_app
    app = MainWindow(isserver=isserver, trayonly=trayonly)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pulsemeeter/interface/main_window.py", line 48, in __init__
    self.windowinstance = self.start_window(isserver)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pulsemeeter/interface/main_window.py", line 103, in start_window
    self.devices['hi'] = self.client.list_hardware_devices('sources')
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pulsemeeter/socket/client.py", line 395, in list_hardware_devices
    return json.loads(self.send_command(f'get-hd {device_type}'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Expected behavior**
Pulsemeeter GUI should appear

**Desktop (please complete the following information):**
 - Distro: Archlinux, rolling, up to date
 - Python Version: Python 3.11.3

**Additional context**

```
[stiw47@archmedia ~]$ sudo pacman -Q pipewire pipewire-pulse gtk3 libappindicator-gtk3 noise-suppression-for-voice pulse-vumeter-git python python-appdirs python-gobject python-pulsectl swh-plugins git python-setuptools glade pipewire-pulse pulseaudio
pipewire 1:0.3.70-2
pipewire-pulse 1:0.3.70-2
gtk3 1:3.24.37-1
libappindicator-gtk3 12.10.0.r298-1
noise-suppression-for-voice 1.03-1
pulse-vumeter-git 0.11.r2.93721e1-1
python 3.11.3-1
python-appdirs 1.4.4-8
python-gobject 3.44.1-3
python-pulsectl 1:23.5.1-1
swh-plugins 0.4.17-4
git 2.40.1-1
python-setuptools 1:67.7.0-1
glade 3.40.0+r14+g1fbca367-2
pipewire-pulse 1:0.3.70-2
pipewire-pulse 1:0.3.70-2
```
Pulsemeeter was installed several times from AUR. Tried with both versions, [pulsemeeter](https://aur.archlinux.org/packages/pulsemeeter) and [pulsemeeter-git](https://aur.archlinux.org/packages/pulsemeeter-git), and got same behavior and same above error.

Virtual input and output devices have been created, and straight after computer reboot, if I try to run Pulsemeeter, I can see on desktop, it switched from default to Virtual_Input_1.

![image](https://github.com/theRealCarneiro/pulsemeeter/assets/3337416/c0a17f61-aa35-4139-a7b7-af8aed768ad7)

![image](https://github.com/theRealCarneiro/pulsemeeter/assets/3337416/16c56c19-5d8e-43c3-8220-04f519304c9e)

Also, if I try to run it, it shows the loading icon on the bottom panel shortly, then icon disappeared and nothing happens:

![image](https://github.com/theRealCarneiro/pulsemeeter/assets/3337416/b09664e7-19c1-4bc7-a1fd-27a12e2416dc)

I think that server is running, just GUI wont start for some reason:

```
[stiw47@archmedia ~]$ pulsemeeter -s
Server: running
Pulseaudio: running
audio server: PulseAudio (on PipeWire 0.3.70)
Pulsemeeter version: 1.2.14
Config File: /home/stiw47/.config/pulsemeeter/config.json
OS: Linux-6.3.3-lqx1-1-lqx-x86_64-with-glibc2.37
Python version: 3.11.3 (main, Apr  5 2023, 15:52:25) [GCC 12.2.1 20230201]
```

I am aware this is not the first issue of this type, especially related with Arch/Manjaro, but I really didn't find solution by reading previous issues, also didn't find same error output in previous issues.

Many thanks in advance.

**Comment by gwydion67** [comment]
same issue, and yes the server starts but no gui shows up

**Comment by wnm210** [comment]
bump

**Comment by theRealCarneiro** [comment]
Fixed on #103
