### ISSUE TITLE
Bluetooth headphones disconnect when pulsemeeter is opened

### ISSUE THREAD

**Issue by ayush123460** [theRealCarneiro/pulsemeeter#12]
Not sure what logs to provide, but as soon as I open pulsemeeter, my bluetooth headphones are disconnected.

**Comment by theRealCarneiro** [comment]
Open the app in a terminal and see if there are any logs, also if you have pavucontrol try opening pulsemeeter while pavucontrol is open and see if pavucontrol will restart it's interface

**Comment by ayush123460** [comment]
Apologies for the delay, here you go:

``` python
Exception in thread Thread-1 (listen_subscribe):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.10/site-packages/pulsemeeter/MainWindow.py", line 434, in listen_subscribe
    for i in self.pulse.subscribe():
  File "/usr/lib/python3.10/site-packages/pulsemeeter/Pulse.py", line 493, in subscribe
    raise subprocess.CalledProcessError(return_code, command)
subprocess.CalledProcessError: Command '['pactl', 'subscribe']' returned non-zero exit status 1.
```

**Comment by theRealCarneiro** [comment]
It seems pulseaudio crashes when you open pulsemeeter, in the latest pull request I added better logs for the app, so if you could install it (only install from source, not yet on pypi) and run it with `pulsemeeter loglevel-all` it would help

**Comment by ayush123460** [comment]
Also, jack is apparently installed
![image](https://user-images.githubusercontent.com/13494534/149431967-d7ed4634-09b5-4658-ab1f-d838a3bb090b.png)

**Comment by theRealCarneiro** [comment]
Delete the configuration file located in ~/.config/pulsemeeter/config.json and try again (forgot to add the key in already existing config files)

**Comment by ayush123460** [comment]
Here you go, from what I understood it is trying to connect the rnnoise monitor to the a2dp sink but failing :thinking: Also it did not disconnect immediately this time, I had to re-apply the noise reduction a couple of times, and noticed that when it's off it doesn't disconnect

```python
pmctl init sink Virtual_Input_1
pmctl init sink Virtual_Input_2
pmctl init sink Virtual_Input_3

pmctl init source Virtual_Output_B1

pmctl init source Virtual_Output_B1
pmctl init source Virtual_Output_B2

pmctl init source Virtual_Output_B1
pmctl init source Virtual_Output_B2
pmctl init source Virtual_Output_B3

pmctl rnnoise hi1_rnnoise alsa_input.pci-0000_00_1f.3.analog-stereo 95 connect 200


pmctl rnnoise  alsa_input.pci-0000_00_1f.3.analog-stereo 95 disconnect 1
pmctl disconnect .monitor bluez_sink.E8_3A_4D_45_FF_3E.a2dp_sink 1
pmctl connect alsa_input.pci-0000_00_1f.3.analog-stereo bluez_sink.E8_3A_4D_45_FF_3E.a2dp_sink 1

pmctl rnnoise  alsa_input.pci-0000_00_1f.3.analog-stereo 95 connect 1
pmctl disconnect alsa_input.pci-0000_00_1f.3.analog-stereo bluez_sink.E8_3A_4D_45_FF_3E.a2dp_sink
pmctl connect .monitor bluez_sink.E8_3A_4D_45_FF_3E.a2dp_sink 1

Error connecting .monitor to bluez_sink.E8_3A_4D_45_FF_3E.a2dp_sink
pmctl disconnect hi1_rnnoise.monitor bluez_sink.E8_3A_4D_45_FF_3E.a2dp_sink 1

pmctl connect hi1_rnnoise.monitor bluez_sink.E8_3A_4D_45_FF_3E.a2dp_sink 1

pmctl disconnect hi1_rnnoise.monitor bluez_sink.E8_3A_4D_45_FF_3E.a2dp_sink

pmctl disconnect hi1_rnnoise.monitor alsa_output.pci-0000_00_1f.3.analog-stereo

pmctl disconnect hi1_rnnoise.monitor bluez_sink.E8_3A_4D_45_FF_3E.a2dp_sink 1

pmctl connect hi1_rnnoise.monitor bluez_sink.E8_3A_4D_45_FF_3E.a2dp_sink 1

pmctl rnnoise hi1_rnnoise alsa_input.pci-0000_00_1f.3.analog-stereo 95 disconnect 1
pmctl disconnect hi1_rnnoise.monitor bluez_sink.E8_3A_4D_45_FF_3E.a2dp_sink 1
pmctl connect alsa_input.pci-0000_00_1f.3.analog-stereo bluez_sink.E8_3A_4D_45_FF_3E.a2dp_sink 1

pmctl rnnoise hi1_rnnoise alsa_input.pci-0000_00_1f.3.analog-stereo 95 connect 1
pmctl disconnect alsa_input.pci-0000_00_1f.3.analog-stereo bluez_sink.E8_3A_4D_45_FF_3E.a2dp_sink
pmctl connect hi1_rnnoise.monitor bluez_sink.E8_3A_4D_45_FF_3E.a2dp_sink 1

Exception in thread Thread-1 (listen_subscribe):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ayush/.local/lib/python3.10/site-packages/pulsemeeter/MainWindow.py", line 449, in listen_subscribe
    for i in self.pulse.subscribe():
  File "/home/ayush/.local/lib/python3.10/site-packages/pulsemeeter/Pulse.py", line 579, in subscribe
    raise subprocess.CalledProcessError(return_code, command)
subprocess.CalledProcessError: Command '['pactl', 'subscribe']' returned non-zero exit status 1.
```

**Comment by theRealCarneiro** [comment]
That might be a noise-supression-for-voice issue, I've had pulseaudio crash on me a few time because of that, instead I just use the plugin that noisetorch uses (same algorithm, but never crashed on me), I've made a [pkgbuild](https://pastebin.com/raw/70ibAVAA) for it if you want to try it (that's only for the plugin, having noisetorch installed is not required and won't conflict but you need still to install this plugin). I'll probably add that to the aur later

**Comment by ayush123460** [comment]
Makes sense. So the pkgbuild installs the ladspa plugin into the folder, but how would it be used? Or does it override the one provided with pulsemeeter?

**Comment by theRealCarneiro** [comment]
It should work out of the box, I already configured pulsemeeter so noisetorch's plugin takes precedence over noise-supression-for-voice

**Comment by ayush123460** [comment]
Alright, will try the noisetorch version. Let's hope it doesn't crash pulseaudio :sweat_smile: Thanks for all the help, I love using pulsemeeter!
