### ISSUE TITLE
Failed to start pulsemeeter. Invalid  json

### ISSUE THREAD

**Issue by GonzaDOD** [theRealCarneiro/pulsemeeter#129]
**Describe the bug**

I can't open the pulsemeeter, there's an error.

**To Reproduce**
1. Go to Terminal
2. Type pulsemeeter
3. See error

**Expected behavior**
I expected the program to open normally

**Screenshots**
![Screenshot_20240916_181156](https://github.com/user-attachments/assets/bbe00759-5a8f-43e9-bc2f-ee34614341fa)

**Desktop (please complete the following information):**
 - Distro: Debian GNU/Linux 12 (bookworm) x86_64 
 - Python Version Python 3.11.2

**Additional context**

When I finished installing pulsemeeter with pip, i got an error running pulsemeeter, the problem was with appindicator3, so i had to install it manually on "https://packages.debian.org/buster/gir1.2-appindicator3-0.1". When i finish, I try to run it again, and I can't start the program:

`ERROR: invalid json 
Traceback (most recent call last):
  File "/home/gonzadev/.local/bin/pulsemeeter", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/gonzadev/.local/pipx/venvs/pulsemeeter/lib/python3.11/site-packages/pulsemeeter/__main__.py", line 481, in main
    start_app(isserver, trayonly)
  File "/home/gonzadev/.local/pipx/venvs/pulsemeeter/lib/python3.11/site-packages/pulsemeeter/__main__.py", line 423, in start_app
    app = MainWindow(isserver=isserver, trayonly=trayonly)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gonzadev/.local/pipx/venvs/pulsemeeter/lib/python3.11/site-packages/pulsemeeter/interface/main_window.py", line 48, in __init__
    self.windowinstance = self.start_window(isserver)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gonzadev/.local/pipx/venvs/pulsemeeter/lib/python3.11/site-packages/pulsemeeter/interface/main_window.py", line 103, in start_window
    self.devices['hi'] = self.client.list_hardware_devices('sources')
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gonzadev/.local/pipx/venvs/pulsemeeter/lib/python3.11/site-packages/pulsemeeter/socket/client.py", line 395, in list_hardware_devices
    return json.loads(self.send_command(f'get-hd {device_type}'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by Prabesh01** [comment]
same here. i tried installing both from aur and pip.
<details>
<summary>pip one gave this error when trying to run pulsemeeter:</summary>

```
Traceback (most recent call last):
  File "/home/prabesh/.venv/bin/pulsemeeter", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/prabesh/.venv/lib/python3.12/site-packages/pulsemeeter/__main__.py", line 481, in main
    start_app(isserver, trayonly)
  File "/home/prabesh/.venv/lib/python3.12/site-packages/pulsemeeter/__main__.py", line 423, in start_app
    app = MainWindow(isserver=isserver, trayonly=trayonly)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/prabesh/.venv/lib/python3.12/site-packages/pulsemeeter/interface/main_window.py", line 48, in __init__
    self.windowinstance = self.start_window(isserver)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/prabesh/.venv/lib/python3.12/site-packages/pulsemeeter/interface/main_window.py", line 102, in start_window
    self.devices['a'] = self.client.list_hardware_devices('sinks')
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/prabesh/.venv/lib/python3.12/site-packages/pulsemeeter/socket/client.py", line 395, in list_hardware_devices
    return json.loads(self.send_command(f'get-hd {device_type}'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 2 (char 1)
```
</details>

<details>
<summary>pulsemeeter-git from aur gave this:</summary>

```
Could not start vumeter for Virtual_Input_3
invalid json from server
App sinks returned an error, audio backend returned error
object of type 'bool' has no len()
Could not join subscribe_thread (maybe there is none)
closing socket

(pulsemeeter:35332): Gtk-CRITICAL **: 18:32:49.395: gtk_main_quit: assertion 'main_loops != NULL' failed
```
</details>

<details>
<summary>pulsemeeter from aur gave this:</summary>

```
Traceback (most recent call last):
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 397, in from_name
    return next(cls.discover(name=name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pulsemeeter", line 33, in <module>
    sys.exit(load_entry_point('pulsemeeter==1.2.14', 'console_scripts', 'pulsemeeter')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/pulsemeeter", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 862, in distribution
    return Distribution.from_name(distribution_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 399, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for pulsemeeter
```
</details>

**Comment by thadigus** [comment]
Same here, I only tried on pulsemeeter-git from AUR.

```shell
λ archlaptop ~ → pulsemeeter
Could not start vumeter for Virtual_Input_3
invalid json from server
App sinks returned an error, audio backend returned error
object of type 'bool' has no len()
Could not join subscribe_thread (maybe there is none)
closing socket

(pulsemeeter:29052): Gtk-CRITICAL **: 12:41:41.010: gtk_main_quit: assertion 'main_loops != NULL' failed
```

**Comment by CrawKatt** [comment]
I also have the same problem, I just installed it and apparently it works since pulseaudio/pipewire detects the virtual inputs but the window does not open. The log is the same

```
└─🕙─[22:49]-(^_^)-[$] pulsemeeter
Could not start vumeter for Virtual_Input_3
invalid json from server
App sinks returned an error, audio backend probably crashed. Server will be closed.
Could not join subscribe_thread (maybe there is none)
closing socket

(pulsemeeter:119305): Gtk-CRITICAL **: 22:49:28.143: gtk_main_quit: assertion 'main_loops != NULL' failed
```
