### ISSUE TITLE
[Bug report] main_loops assertion fails, causing the program to stay alive

### ISSUE THREAD

**Issue by KrischnaGabriel** [theRealCarneiro/pulsemeeter#50]
**Describe the bug**
pulsemeeter does not terminate correctly and needs to be forcefully closed.

**To Reproduce**
1. Open pulsemeeter (from a terminal `$ pulsemeeter`)
2. Open the configs (top right corner) and change the layout to tabbed.
3. Change the layout back to default
4. Close pulsemeeter (tray icon -> right click -> Close)

**Actual behavior**
The window becomes unresponsive and pulsemeeter stays open.
(To terminate pulsemeeter from this frozen state, simply pressing ctrl+C in the terminal pulsemeeter is running in, works)

**Expected behavior**
That pulsemeeter would close as it does normally when skipping step 2 and 3.

**Desktop:**
 - Distro: Linux Mint 20.3 Cinnamon
 - Python Version 3.8.10

### Additional context

**Installation Procedure and Dependencies**
The installation of pulsemeeter went exactly as guided here: (Ubuntu and the Pypi package)
https://github.com/theRealCarneiro/pulsemeeter/wiki/Installation#installing-dependencies

**Installed Dependencies:**

**pip:**
python-pip-whl/focal-updates,focal-updates,now 20.0.2-5ubuntu1.6 all [installed,automatic]
python3-pip/focal-updates,focal-updates,now 20.0.2-5ubuntu1.6 all [installed]

**libappindicator:**
libappindicator1/focal,now 12.10.1+20.04.20200408.1-0ubuntu1 amd64 [installed,automatic]
libappindicator3-1/focal,now 12.10.1+20.04.20200408.1-0ubuntu1 amd64 [installed]
libappindicator3-dev/focal,now 12.10.1+20.04.20200408.1-0ubuntu1 amd64 [installed]

**gobject-introspection:**
gobject-introspection/focal-updates,now 1.64.1-1~ubuntu20.04.1 amd64 [installed]

**libpulse:**
libpulse-dev/focal-updates,now 1:13.99.1-1ubuntu3.13 amd64 [installed]
libpulse-mainloop-glib0/focal-updates,now 1:13.99.1-1ubuntu3.13 amd64 [installed]
libpulse0/focal-updates,now 1:13.99.1-1ubuntu3.13 amd64 [installed]
libpulse0/focal-updates,now 1:13.99.1-1ubuntu3.13 i386 [installed,automatic]
libpulsedsp/focal-updates,now 1:13.99.1-1ubuntu3.13 amd64 [installed]

### Logs
Since I started pulsemeeter in a terminal I have console outputs.
When discovering the bug I cannot recall what exactly I all did, but i have this console log:

> Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pulsemeeter/interface/vumeter_widget.py", line 39, in listen_peak
    self.process = subprocess.Popen(command,
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pulse-vumeter'
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pulsemeeter/interface/vumeter_widget.py", line 39, in listen_peak
    self.process = subprocess.Popen(command,
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pulse-vumeter'
/usr/lib/python3/dist-packages/gi/overrides/Gtk.py:1632: Warning: g_object_notify: assertion 'G_IS_OBJECT (object)' failed
  return _Gtk_main(*args, **kwargs)
/usr/lib/python3/dist-packages/gi/overrides/Gtk.py:1632: Warning: g_object_set: assertion 'G_IS_OBJECT (object)' failed
  return _Gtk_main(*args, **kwargs)
closing client handler threads...
(pulsemeeter:225675): Gtk-CRITICAL **: 20:17:58.240: gtk_main_quit: assertion 'main_loops != NULL' failed
sending exit signal to listener thread, it should exit within 2 seconds...
closing socket

The second time when reproducing the error in the steps described above, a few less errors occurred, but the main_loops assertion at the end still failed:

> user@FUJITSU:~$ pulsemeeter 
/bin/sh: 1: connect: not found
/usr/lib/python3/dist-packages/gi/overrides/Gtk.py:1632: Warning: g_object_notify: assertion 'G_IS_OBJECT (object)' failed
  return _Gtk_main(*args, **kwargs)
/usr/lib/python3/dist-packages/gi/overrides/Gtk.py:1632: Warning: g_object_set: assertion 'G_IS_OBJECT (object)' failed
  return _Gtk_main(*args, **kwargs)
closing client handler threads...
(pulsemeeter:228912): Gtk-CRITICAL **: 20:21:50.649: gtk_main_quit: assertion 'main_loops != NULL' failed
closing socket
sending exit signal to listener thread, it should exit within 2 seconds...

**Comment by theRealCarneiro** [comment]
Fixed it in https://github.com/theRealCarneiro/pulsemeeter/commit/8271da04da22ac6b0b7aa2ff9ae8a56ed1f0a6f6, can you try it out?

**Comment by KrischnaGabriel** [comment]
Yes it's fixed! tho the console output doesn't look so good. There apparently are still tons of exceptions occurring.

>$ /home/user/.local/bin/pulsemeeter 
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/pulsemeeter/interface/vumeter_widget.py", line 40, in listen_peak
    self.process = subprocess.Popen(command,
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
Exception in thread Thread-8:
  File "/home/user/.local/lib/python3.8/site-packages/pulsemeeter/interface/vumeter_widget.py", line 40, in listen_peak
Traceback (most recent call last):
Exception in thread Thread-7:
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    raise child_exception_type(errno_num, err_msg, err_filename)
    self.process = subprocess.Popen(command,
FileNotFoundError: [Errno 2] No such file or directory: 'pulse-vumeter'
    self.run()
Traceback (most recent call last):
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    self._target(*self._args, **self._kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/pulsemeeter/interface/vumeter_widget.py", line 40, in listen_peak
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
Exception in thread Thread-9:
    self.process = subprocess.Popen(command,
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._target(*self._args, **self._kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/pulsemeeter/interface/vumeter_widget.py", line 40, in listen_peak
    raise child_exception_type(errno_num, err_msg, err_filename)
    self._execute_child(args, executable, preexec_fn, close_fds,
FileNotFoundError: [Errno 2] No such file or directory: 'pulse-vumeter'
    self.process = subprocess.Popen(command,
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self.run()
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    self._target(*self._args, **self._kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/pulsemeeter/interface/vumeter_widget.py", line 40, in listen_peak
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pulse-vumeter'
    self.process = subprocess.Popen(command,
    raise child_exception_type(errno_num, err_msg, err_filename)
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
FileNotFoundError: [Errno 2] No such file or directory: 'pulse-vumeter'
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
Exception in thread Thread-10:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pulse-vumeter'
    self.run()
Exception in thread Thread-11:
  File "/usr/lib/python3.8/threading.py", line 870, in run
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/pulsemeeter/interface/vumeter_widget.py", line 40, in listen_peak
    self.process = subprocess.Popen(command,
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pulse-vumeter'
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
Exception in thread Thread-12:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/pulsemeeter/interface/vumeter_widget.py", line 40, in listen_peak
    self.process = subprocess.Popen(command,
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
    self._target(*self._args, **self._kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/pulsemeeter/interface/vumeter_widget.py", line 40, in listen_peak
FileNotFoundError: [Errno 2] No such file or directory: 'pulse-vumeter'
    self.process = subprocess.Popen(command,
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pulse-vumeter'
Exception in thread Thread-14:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
Exception in thread Thread-15:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
Exception in thread Thread-16:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
Exception in thread Thread-17:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/pulsemeeter/interface/vumeter_widget.py", line 40, in listen_peak
    self._target(*self._args, **self._kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/pulsemeeter/interface/vumeter_widget.py", line 40, in listen_peak
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/pulsemeeter/interface/vumeter_widget.py", line 40, in listen_peak
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/pulsemeeter/interface/vumeter_widget.py", line 40, in listen_peak
Exception in thread Thread-18:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/pulsemeeter/interface/vumeter_widget.py", line 40, in listen_peak
    self.process = subprocess.Popen(command,
    self.process = subprocess.Popen(command,
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self.process = subprocess.Popen(command,
Exception in thread Thread-19:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.process = subprocess.Popen(command,
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self.process = subprocess.Popen(command,
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
Exception in thread Thread-20:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/pulsemeeter/interface/vumeter_widget.py", line 40, in listen_peak
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._execute_child(args, executable, preexec_fn, close_fds,
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pulse-vumeter'
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    self.process = subprocess.Popen(command,
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
Exception in thread Thread-21:
    raise child_exception_type(errno_num, err_msg, err_filename)
  File "/home/user/.local/lib/python3.8/site-packages/pulsemeeter/interface/vumeter_widget.py", line 40, in listen_peak
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pulse-vumeter'
    self._execute_child(args, executable, preexec_fn, close_fds,
FileNotFoundError: [Errno 2] No such file or directory: 'pulse-vumeter'
Traceback (most recent call last):
    self.process = subprocess.Popen(command,
    self._execute_child(args, executable, preexec_fn, close_fds,
    raise child_exception_type(errno_num, err_msg, err_filename)
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
FileNotFoundError: [Errno 2] No such file or directory: 'pulse-vumeter'
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._execute_child(args, executable, preexec_fn, close_fds,
FileNotFoundError: [Errno 2] No such file or directory: 'pulse-vumeter'
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
    self._target(*self._args, **self._kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/pulsemeeter/interface/vumeter_widget.py", line 40, in listen_peak
FileNotFoundError: [Errno 2] No such file or directory: 'pulse-vumeter'
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pulse-vumeter'
    self.process = subprocess.Popen(command,
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pulse-vumeter'
Exception in thread Thread-23:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/pulsemeeter/interface/vumeter_widget.py", line 40, in listen_peak
    self.process = subprocess.Popen(command,
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
Exception in thread Thread-24:
Traceback (most recent call last):
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pulse-vumeter'
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/pulsemeeter/interface/vumeter_widget.py", line 40, in listen_peak
    self.process = subprocess.Popen(command,
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pulse-vumeter'
Exception in thread Thread-25:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
Exception in thread Thread-26:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/pulsemeeter/interface/vumeter_widget.py", line 40, in listen_peak
    self.process = subprocess.Popen(command,
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/pulsemeeter/interface/vumeter_widget.py", line 40, in listen_peak
    self.process = subprocess.Popen(command,
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pulse-vumeter'
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
Exception in thread Thread-27:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/pulsemeeter/interface/vumeter_widget.py", line 40, in listen_peak
    self.process = subprocess.Popen(command,
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pulse-vumeter'
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pulse-vumeter'
Exception in thread Thread-28:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/pulsemeeter/interface/vumeter_widget.py", line 40, in listen_peak
    self.process = subprocess.Popen(command,
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
Exception in thread Thread-29:
Traceback (most recent call last):
Exception in thread Thread-30:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pulse-vumeter'
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/pulsemeeter/interface/vumeter_widget.py", line 40, in listen_peak
    self.process = subprocess.Popen(command,
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pulse-vumeter'
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/pulsemeeter/interface/vumeter_widget.py", line 40, in listen_peak
    self.process = subprocess.Popen(command,
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pulse-vumeter'
/usr/lib/python3/dist-packages/gi/overrides/Gtk.py:1632: Warning: g_object_notify: assertion 'G_IS_OBJECT (object)' failed
  return _Gtk_main(*args, **kwargs)
/usr/lib/python3/dist-packages/gi/overrides/Gtk.py:1632: Warning: g_object_set: assertion 'G_IS_OBJECT (object)' failed
  return _Gtk_main(*args, **kwargs)
closing client handler threads...
(pulsemeeter:692183): Gtk-CRITICAL **: 18:20:06.442: gtk_main_quit: assertion 'main_loops != NULL' failed
closing socket
sending exit signal to listener thread, it should exit within 2 seconds...
