### ISSUE TITLE
pulsemeeter does not want to start

### ISSUE THREAD

**Issue by Monstanner** [theRealCarneiro/pulsemeeter#65]
**Describe the bug**
I can't open pulsemeeter. No window appears / gets stuck at startup.

**To Reproduce**
1. Open pulsemeeter

**Expected behavior**
The pulsemeeter starts normally.

**Desktop (please complete the following information):**
 - Distro: Arch Linux
 - Python Version 3.10.5

**Additional context**
The console outputs the following:

pulsemeeter 1.2.14-1:

```
Traceback (most recent call last):
  File "/usr/bin/pulsemeeter", line 33, in <module>
    sys.exit(load_entry_point('pulsemeeter==1.2.14', 'console_scripts', 'pulsemeeter')())
  File "/usr/lib/python3.10/site-packages/pulsemeeter/__main__.py", line 481, in main
    start_app(isserver, trayonly)
  File "/usr/lib/python3.10/site-packages/pulsemeeter/__main__.py", line 423, in start_app
    app = MainWindow(isserver=isserver, trayonly=trayonly)
  File "/usr/lib/python3.10/site-packages/pulsemeeter/interface/main_window.py", line 48, in __init__
    self.windowinstance = self.start_window(isserver)
  File "/usr/lib/python3.10/site-packages/pulsemeeter/interface/main_window.py", line 103, in start_window
    self.devices['hi'] = self.client.list_hardware_devices('sources')
  File "/usr/lib/python3.10/site-packages/pulsemeeter/socket/client.py", line 395, in list_hardware_devices
    return json.loads(self.send_command(f'get-hd {device_type}'))
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
(Quit with CTRL+C)
^CException ignored in: <module 'threading' from '/usr/lib/python3.10/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1567, in _shutdown
    lock.acquire()
KeyboardInterrupt:
```

pulsemeeter-git 1.2.14.r27.1e681c5-1:
```

Traceback (most recent call last):
  File "/usr/bin/pulsemeeter", line 33, in <module>
    sys.exit(load_entry_point('pulsemeeter==1.2.15', 'console_scripts', 'pulsemeeter')())
  File "/usr/lib/python3.10/site-packages/pulsemeeter/__main__.py", line 512, in main
    start_app(isserver, trayonly)
  File "/usr/lib/python3.10/site-packages/pulsemeeter/__main__.py", line 448, in start_app
    MainWindow(isserver=isserver, trayonly=trayonly)
  File "/usr/lib/python3.10/site-packages/pulsemeeter/interface/main_window.py", line 46, in __init__
    self.windowinstance = self.start_window(isserver)
  File "/usr/lib/python3.10/site-packages/pulsemeeter/interface/main_window.py", line 96, in start_window
    self.devices['hi'] = self.client.list_hardware_devices('sources')
  File "/usr/lib/python3.10/site-packages/pulsemeeter/socket/client.py", line 389, in list_hardware_devices
    return json.loads(self.send_command(f'get-hd {device_type}'))
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
(Quit with CTRL+C)
Exception ignored in: <module 'threading' from '/usr/lib/python3.10/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1567, in _shutdown
    lock.acquire()
KeyboardInterrupt

```

**Comment by ZerkerEOD** [comment]
Following for solution.

**Comment by ZerkerEOD** [comment]
I got this running by installing a ton of Pipewire stuff and having that over pulseaudio.

**Comment by Monstanner** [comment]
> I got this running by installing a ton of Pipewire stuff and having that over pulseaudio.

I installed `pulseaudio-alsa` & `Pipewire`. However, if I want to install `pulseaudio`, Arch tells me that he wants to uninstall `Pipewire-pulse`. The problem is that the GUI does not want to start.

**Comment by Fl1tzi** [comment]
@Monstanner You cannot run Pulseaudio and Pipewire at the same time because you can only run one sound server at a time. I would not recommend installing any packages and hoping that they work. It's not just installing Pipewire as a package and you are ready. Please first of all read the Arch Wiki pages for both and then compare them and try to understand the difference (I would also read [this](https://docs.pipewire.org/index.html) to understand what you need). Pulseaudio is actually for the current version of Pulsemeeter better (as seen in #7 ). This isn't a proper solution and the next update (where Pipewire probably will be superior) will fix this issue. The GUI probably doesn't start as you are missing the `pipewire-pulse` package. If you need help setting some things up you maybe want to join our Discord and get help there. https://discord.gg/ekWt9NuEWv

**Comment by Monstanner** [comment]
> @Monstanner You cannot run Pulseaudio and Pipewire at the same time because you can only run one sound server at a time. I would not recommend installing any packages and hoping that they work. It's not just installing Pipewire as a package and you are ready. Please first of all read the Arch Wiki pages for both and then compare them and try to understand the difference (I would also read [this](https://docs.pipewire.org/index.html) to understand what you need). Pulseaudio is actually for the current version of Pulsemeeter better (as seen in #7 ). This isn't a proper solution and the next update (where Pipewire probably will be superior) will fix this issue. The GUI probably doesn't start as you are missing the `pipewire-pulse` package. If you need help setting some things up you maybe want to join our Discord and get help there. https://discord.gg/ekWt9NuEWv

Thanks for the hint and the help. I needed pulsemeeter to record desktop audio in Tenacity. I managed to do it without pulsemeete. From my point of view, this issue can be closed.

**Comment by Fl1tzi** [comment]
I will let it open until the fix is in the main branch.

**Comment by OBKF** [comment]
Same issue here.
