### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'connect'

### ISSUE THREAD

**Issue by auvio323** [theRealCarneiro/pulsemeeter#99]
**Describe the bug**
Pulsemeeter does not launch and instead brings up an error

**To Reproduce**
1. Run Pulsemeeter command
2. See the following error: `[WARNING] in [vumeter_widget]: Could not start vumeter for Virtual_Input_3
Traceback (most recent call last):
  File "/usr/bin/pulsemeeter", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/pulsemeeter/__main__.py", line 554, in main
    start_app(isserver, trayonly)
  File "/usr/lib/python3.10/site-packages/pulsemeeter/__main__.py", line 483, in start_app
    MainWindow(isserver=isserver, trayonly=trayonly)
  File "/usr/lib/python3.10/site-packages/pulsemeeter/interface/main_window.py", line 50, in __init__
    self.windowinstance = self.start_window(isserver)
  File "/usr/lib/python3.10/site-packages/pulsemeeter/interface/main_window.py", line 131, in start_window
    event_label.connect('button_press_event', self.port_select_popover, device_type, device_id)
AttributeError: 'NoneType' object has no attribute 'connect'

`

**Expected behavior**
Pulsemeeter will open up with a GUI and not bring up an error

**Desktop (please complete the following information):**
 - Distro: Arch Linux
 - Python 3.10.7

**Additional context**
I am on the nightly build because I am using pipewire. When I use stable, it brings me this error: `invalid json from server
App sinks returned an error, audio backend probably crashed. Server will be closed.
Could not join subscribe_thread (maybe there is none)
closing client handler threads...
closing socket
sending exit signal to listener thread, it should exit within 2 seconds...`
It used to work fine for about 30 seconds before I changed the settings layout to "tabbed" which froze at first, then crashed, and then wouldn't launch again. I deleted the config, reinstalled a bunch of times, and I am still met with this error. Any help would be greatly appreciated.

**Comment by heylix** [comment]
I have the same issue, also under Arch Linux and also after changing the layout to tabbed. Trying the nightly build after #103 has been linked to this issue.

**Comment by theRealCarneiro** [comment]
Old config files break in the latest build, I'll add a warning

**Comment by heylix** [comment]
Nice, that's a good idea. You might also want to make it v2.0.0 as SemVer dictates breaking changes mean a new major version. Not dictating you what to do, only a suggestion :)

**Comment by theRealCarneiro** [comment]
Fixed in #103
